/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublishersRouteImport } from './routes/publishers'
import { Route as GenresRouteImport } from './routes/genres'
import { Route as AuthorsRouteImport } from './routes/authors'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as BooksNewRouteImport } from './routes/books/new'
import { Route as BooksBookIdRouteImport } from './routes/books/$bookId'

const PublishersRoute = PublishersRouteImport.update({
  id: '/publishers',
  path: '/publishers',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresRoute = GenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsRoute = AuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksNewRoute = BooksNewRouteImport.update({
  id: '/books/new',
  path: '/books/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authors': typeof AuthorsRoute
  '/genres': typeof GenresRoute
  '/publishers': typeof PublishersRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/new': typeof BooksNewRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/books/': typeof BooksIndexRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authors': typeof AuthorsRoute
  '/genres': typeof GenresRoute
  '/publishers': typeof PublishersRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/new': typeof BooksNewRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/books': typeof BooksIndexRoute
  '/orders': typeof OrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authors': typeof AuthorsRoute
  '/genres': typeof GenresRoute
  '/publishers': typeof PublishersRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/new': typeof BooksNewRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/books/': typeof BooksIndexRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authors'
    | '/genres'
    | '/publishers'
    | '/books/$bookId'
    | '/books/new'
    | '/orders/$orderId'
    | '/books/'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authors'
    | '/genres'
    | '/publishers'
    | '/books/$bookId'
    | '/books/new'
    | '/orders/$orderId'
    | '/books'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/authors'
    | '/genres'
    | '/publishers'
    | '/books/$bookId'
    | '/books/new'
    | '/orders/$orderId'
    | '/books/'
    | '/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorsRoute: typeof AuthorsRoute
  GenresRoute: typeof GenresRoute
  PublishersRoute: typeof PublishersRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  BooksNewRoute: typeof BooksNewRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  BooksIndexRoute: typeof BooksIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/publishers': {
      id: '/publishers'
      path: '/publishers'
      fullPath: '/publishers'
      preLoaderRoute: typeof PublishersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres': {
      id: '/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/new': {
      id: '/books/new'
      path: '/books/new'
      fullPath: '/books/new'
      preLoaderRoute: typeof BooksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorsRoute: AuthorsRoute,
  GenresRoute: GenresRoute,
  PublishersRoute: PublishersRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  BooksNewRoute: BooksNewRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  BooksIndexRoute: BooksIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
